@description Orpheus Lite Console (chmaha)
@author chmaha
@version 1.5
@changelog
  Remove UINT32_MAX references
@metapackage
@provides
  Orpheus_Lite_Channel.jsfx
  Orpheus_Lite_Bus.jsfx
@about
  These jsfx analog console emulation plugins use DSP from airwindows Console8Lite.
  Also included is the Orpheus Lite project template with plugins already in place (requires MagicFairyDust and RCGain to be installed)
